[[inputs.gnmi]]
  addresses = [ "${ACX_ADDRESSES}" ]
  username = "${GNMI_USERNAME}"
  password = "${GNMI_PASSWORD}"
  tls_enable = true
  insecure_skip_verify = true
  encoding = "proto"
  redial = "60s"
  path_guessing_strategy = "subscription" 

  [[inputs.gnmi.subscription]]
    name = "SYSTEM"
    path = "/system/state/hostname"
    sample_interval = "30s"
    subscription_mode = "sample"

  [[inputs.gnmi.subscription]]
    name = "INTERFACES"
    path = "/interfaces/interface/state/counters"
    sample_interval = "30s"
    subscription_mode = "sample"
