### INTERFACES
[[inputs.gnmi]]
  addresses = [ "${ACX_ADDRESSES}" ]
  username = "${GNMI_USERNAME}"
  password = "${GNMI_PASSWORD}" 
  tls_enable = true
  insecure_skip_verify = true
  encoding = "proto"
  redial = "60s"
  path_guessing_strategy = "subscription"
  depth = 5

  [[inputs.gnmi.subscription]]
    name = "COMPONENT_STATE"
    path = "/components/component/state"
    sample_interval = "60s"
    subscription_mode = "sample"
