[[processors.converter]]
  namepass = ["BGP_SESSION_STATE"]
  [processors.converter.tags]
    string = ["session_state"]

[[processors.enum]]
  namepass = ["BGP_SESSION_STATE"]
  [[processors.enum.mapping]]
    field = "session_state"
    [processors.enum.mapping.value_mappings]
      "IDLE" = 1
      "ACTIVE" = 2
      "CONNECT" = 3
      "ESTABLISHED" = 4

[[processors.converter]]
  namepass = ["BGP_STATE"]
  [processors.converter.fields]
    float = ["last_established"]

[[processors.starlark]]
  namepass = ["BGP_STATE"]
  source = '''
def apply(metric):
  if "last_established" in metric.fields:
    metric.fields["last_established"] = float(metric.fields["last_established"]) / 1e9
  return metric
'''
