{
 "title": "Juniper-gNMI",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "OSPF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "OSPF NEIGHBOUR STATE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OSPF_Neighbors_state_adjacency_state",
     "legendFormat": "{{router_id}} via {{id}}"
    }
   ]
  },
  {
   "title": "NEIGHOUR INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max_over_time(OSPF_Neighbors_state_adjacency_state[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BGP INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "BGP STATUS SESSION", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 } },
  {
   "title": "MAX USED PORT BGP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "BGP_STATE_neighbor_port", "legendFormat": "{{neighbor_address}}" }
   ]
  },
  {
   "title": "LAST BGP ESTABLISHED",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "BGP_STATE_last_established * 1000",
     "legendFormat": "{{neighbor_address}}"
    }
   ]
  },
  { "title": "OPTICAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "TRANSMITER IN POWER",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by (name) (OPTICAL_POWER_input_power_instant)\r\n",
     "legendFormat": "{{name}} in"
    }
   ]
  },
  {
   "title": "TRANSMITER OUT POWER",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by (name) (OPTICAL_POWER_output_power_instant)\r\n",
     "legendFormat": "{{port_sortable}} {{name}} out"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "TOP 3 INTERFACE ET-* (IN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_COUNTERS_in_octets{name=~\"et-.+|l.+\"}[1m]) * 8)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 3 INTERFACE ET-* (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_COUNTERS_out_octets{name=~\"et-.+|l.+\"}[1m]) * 8)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 3 MGMT IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_COUNTERS_in_octets{name=~\"^re.*\"}[1m]) * 8) \r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "TOP PROCESS USAGE CPU",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "topk(20,PROCESSES_cpu_utilization)\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Power used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (name) (COMPONENT_STATE_used_power{name=~\"^PSM.*\"})\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 88 },
   "targets": [
    {
     "expr": "100 * avg by(instance) (\r\n  COMPONENT_STATE_memory_utilized\r\n) /\r\navg by(instance) (\r\n  COMPONENT_STATE_memory_available + COMPONENT_STATE_memory_utilized\r\n)\r\n",
     "legendFormat": "ram %"
    }
   ]
  },
  {
   "title": "AVG temp for chassis and fpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(TEMP_instant) by (source)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "QUEUE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "QUEUE transmit octets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (interface_id, name) (rate(QUEUE_STATE_queue_state_transmit_octets))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUEUE Transmit pkts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 105 },
   "targets": [
    {
     "expr": "sum by (interface_id, name) (rate(QUEUE_STATE_queue_state_transmit_pkts))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUEUE DROP Octets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (interface_id, name) (rate(QUEUE_STATE_queue_state_dropped_octets))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUEUE DROP PKTS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 119 },
   "targets": [
    {
     "expr": "sum by (interface_id, name) (rate(QUEUE_STATE_queue_state_dropped_pkts))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}