services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - victoriametrics
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN

volumes:
  grafana-data:
