volumes:
  grafana-data:
  grafana-provisioning:   
  vm-data:               

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - vm-data:/storage     
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana                  
      - grafana-provisioning:/etc/grafana/provisioning 
    restart: unless-stopped

  telegraf:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIBS=all
    container_name: telegraf
    env_file:
      - .env
    depends_on:
      - victoriametrics
    command: --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf.d:/etc/telegraf/telegraf.d:ro
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN

