[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "30s"
  omit_hostname = true

[[inputs.snmp]]
  agents = ["10.250.249.165"]
  version = 3

  sec_name = "${SNMP_SEC_NAME}"
  auth_protocol = "MD5"
  auth_password = "${SNMP_AUTH_PASS}"
  sec_level = "authPriv"
  priv_protocol = "DES"
  priv_password = "${SNMP_PRIV_PASS}"

  name_prefix = "juniper_"
  timeout = "5s"
  retries = 3

[[inputs.prometheus]]
  urls = ["http://10.250.249.169:9100/metrics"]
  name_prefix = "ubuntuVM_"


[[outputs.http]]
  url = "http://victoriametrics:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"   # format tekstowym, nie natywny