[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "30s"
  omit_hostname = true

[[inputs.prometheus]]
  urls = ["http://10.250.249.169:9100/metrics"]
  name_prefix = "ubuntuVM_"
  
[[outputs.http]]
  url = "http://victoriametrics:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"   # format tekstowym, nie natywny
