[[outputs.file]]
  files = ["stdout"]
  data_format = "prometheus"

[[outputs.http]]
  url = "http://victoriametrics:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"   # format tekstowym, nie natywny
