[[inputs.syslog]]
  server = "udp://:514"
  best_effort = true


[[processors.regex]]
  namepass = ["syslog"]
  [[processors.regex.fields]]
    key = "message"
    pattern = "dhcp,info %{IP:ip_address} assigned"
    replacement = "${ip_address}"
    result_key = "leased_ip"
