

[[outputs.http]]
  url = "http://victoriametrics:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"

# [[outputs.influxdb]]
#   urls = ["http://victoriametrics:8428"] 
#   database = "telegraf"                  
#   skip_database_creation = true         
#   content_encoding = "gzip"             
#   precision = "s"                    
