
volumes:
  grafana-data:
  victoria-metrics-data:
  
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - /opt/victoria-metrics-data:/victoria-metrics-data
    command:
      - -retentionPeriod=12
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - victoriametrics
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf.d:/etc/telegraf/telegraf.d:ro
    command: --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN


