{
 "title": "Mikrotik",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_uptime_seconds{MIBS!~\".*\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP Lease",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "mikrotik_dhcp_lease{MIBS!~\".*\"}",
     "legendFormat": "DHCP info"
    }
   ]
  },
  {
   "title": "WLAN NOISE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "mikrotik_noise_floor_wlan1{MIBS!~\".*\"}",
     "legendFormat": "wlan1"
    },
    {
     "expr": "mikrotik_noise_floor_wlan2{MIBS!~\".*\"}",
     "legendFormat": "wlan2"
    }
   ]
  },
  {
   "title": "CPU FREQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mikrotik_cpu_frequency{agent_host=\"192.168.1.22\", MIBS!~\".*\"}\r\n",
     "legendFormat": "CPU Frequency"
    }
   ]
  },
  {
   "title": "Traffic ETHER3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(mikrotik_ifInOctets_ether3{MIBS!~\".*\"})",
     "legendFormat": "INCOMING "
    },
    {
     "expr": "rate(mikrotik_ifOutOctets_ether3{MIBS!~\".*\"})",
     "legendFormat": "OUTCOMING"
    }
   ]
  },
  {
   "title": "Disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "(mikrotik_total_memory{MIBS!~\".*\"} - mikrotik_used_memory{MIBS!~\".*\"})/ mikrotik_total_memory{MIBS!~\".*\"}*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}