{
 "title": "Juniper-gNMI",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "BGP INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "BGP STATUS SESSION", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "OPTICAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OPTICAL_COS JESzze nwm co ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "avg by(name) (OPTIC_physical_channels_channel_state_input_power_instant > -30\r\nand\r\nOPTIC_physical_channels_channel_state_output_power_instant > -10)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "TOP 3 INTERFACE ET-* (IN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_in_octets{name=~\"^(et|lo).*\"}[1m]) * 8)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 3 INTERFACE ET-* (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_out_octets{name=~\"^(et|lo).*\"}[1m]) * 8)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 10 VLAN IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(SUBINTERFACES_in_octets[1m])) by (index)) *8 \r\n",
     "legendFormat": "vlan {{index}}"
    }
   ]
  },
  {
   "title": "TOP 10 VLAN OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(SUBINTERFACES_out_octets[1m])) by (index)) *8 \r\n",
     "legendFormat": "vlan {{index}}"
    }
   ]
  },
  {
   "title": "TOP 3 MGMT IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(3, rate(INTERFACES_in_octets{name=~\"^re.*\"}[1m]) * 8)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "AVG temp for chassis and fpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(TEMP_instant) by (source)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "100 * COMPONENT_STATE_memory_utilized / (COMPONENT_STATE_memory_available + COMPONENT_STATE_memory_utilized)\r\n",
     "legendFormat": "ram %"
    }
   ]
  },
  {
   "title": "Power used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENT_STATE_used_power{name=~\"^PSM.*\"}\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "QUEUE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "QUEUE_queue_state_max_queue_len\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}