[[processors.converter]]
  namepass = ["BGP_SESSION_STATE"]
  [processors.converter.tags]
    string = ["session_state"]

[[processors.converter]]
  namepass = ["BGP_STATE"]
  [processors.converter.fields]
    float = ["last_established"]

[[processors.converter]]
  [processors.converter.fields]
    tag = ["name", "pid"]

[[processors.converter]]
  namepass = ["QUEUE_STATE"]
  [processors.converter.fields]
    drop = ["queue/name", "queue/state/name"]

[[processors.converter]]
  namepass = ["ARP_Neighbors"]
  [processors.converter.fields]
    tag = ["link_layer_address", "interface_name"]

[[processors.converter]]
  namepass = ["QUEUE_STATE"]
  [processors.converter.fields]
    drop = ["queue/name", "queue/state/name"]

[[processors.converter]]
  namepass = ["OSPF_Neighbors"]
  order = 20
  [processors.converter.fields]
    tag = [
      "neighbor_id",
      "designated_router",
      "backup_designated_router"
    ]

[[processors.converter]]
  namepass = ["OSPF_Interfaces"]
  order = 12
  [processors.converter.fields]
    tag = [
    "network_type",
    ]  

[[processors.converter]]
  namepass = ["OSPF_LSDB"]
  order = 12
  [processors.converter.fields]
    tag = [
    "lsa_adv_router",
    "lsa_link_state_id",
    "lsa_link_id",
    "lsa_link_data",
    "router_lsa_link_id",
    "router_lsa_link_data"
    ]  
  
  