[[processors.converter]]
  namepass = ["BGP_SESSION_STATE"]
  [processors.converter.tags]
    string = ["session_state"]

[[processors.converter]]
  namepass = ["BGP_STATE"]
  [processors.converter.fields]
    float = ["last_established"]

[[processors.converter]]
  namepass = ["OSPF_Neighbors"]
  [processors.converter.fields]
    string = ["state/adjacency_state"]
  [processors.converter.tags]
    string = ["state/adjacency_state"]

[[processors.converter]]
  [processors.converter.fields]
    tag = ["name", "pid"]

[[processors.converter]]
  namepass = ["QUEUE_STATE"]
  [processors.converter.fields]
    drop = ["queue/name", "queue/state/name"]

[[processors.converter]]
  namepass = ["ARP_Neighbors"]
  [processors.converter.fields]
    tag = ["link_layer_address", "interface_name"]

[[processors.converter]]
  namepass = ["QUEUE_STATE"]
  [processors.converter.fields]
    drop = ["queue/name", "queue/state/name"]
