
[[processors.enum]]
  namepass = ["ARP_Neighbors"]
  [[processors.enum.mapping]]
    field = "neighbor_state"
    [processors.enum.mapping.value_mappings]
      "REACHABLE" = 1
      "STALE"     = 2
      "DELAY"     = 3

[[processors.enum]]
  namepass = ["ARP_Neighbors"]
  [[processors.enum.mapping]]
    field = "origin"
    [processors.enum.mapping.value_mappings]
      DYNAMIC = 1
      STATIC  = 2


[[processors.enum]]
  namepass = ["OSPF_Neighbors"]
  [[processors.enum.mapping]]
    field = "state/adjacency_state"
    [processors.enum.mapping.value_mappings]
      "DOWN" = 0
      "INIT" = 1
      "TWO_WAY" = 2
      "EXSTART" = 3
      "EXCHANGE" = 4
      "LOADING" = 5
      "FULL" = 6


[[processors.enum]]
  namepass = ["BGP_SESSION_STATE"]
  [[processors.enum.mapping]]
    fields = ["session_state"]
    [processors.enum.mapping.value_mappings]
      "DOWN" = 0
      "IDLE" = 1
      "ACTIVE" = 2
      "CONNECT" = 3
      "ESTABLISHED" = 4
      "OPENCONFIRM" = 5
      "OPENSENT" = 6