[[processors.filter]]
  namepass = ["INTERFACES_COUNTERS","INTERFACES_TRANSCEIVER"]

  fielddrop = [
    "out_queue/*",
    "in_multicast_pkts",
    "out_multicast_pkts",
    "in_broadcast_pkts",
    "out_broadcast_pkts",
    "in_unicast_pkts",
    "out_unicast_pkts",
    "last_clear",
    "transceiver",
    "init-time", "init_time",
    "parent-ae-name", "parent_ae_name",
    "hardware-port", "hardware_port",
    "physical-channel", "physical_channel",
    "name"
  ]

  tagdrop = ["path","host","system_id"]


[[processors.filter]]
  namepass  = ["SUBINTERFACES_STATE","SUBINTERFACES_COUNTERS"]
  tagdrop   = ["path","host","system_id"]
  fielddrop = [
    "description",
    "enabled",
    "management",
    "cpu"
  ]

[[processors.filter]]
  namepass  = ["OPTICAL_POWER"]
  tagdrop   = ["path","host","system_id"]
  fielddrop = [
    "form_factor", "form_factor_preconf",
    "connector_type",
    "vendor*", "serial_no", "date_code",
    "ethernet_pmd*", "sonet_sdh_compliance_code", "otn_compliance_code",
    "module_functional_type",
    "enabled", "present",
    "fault_condition",
    "fec_mode", "fec_status",
    "fec_corrected_bits", "fec_uncorrectable_blocks",
  ]

