[[processors.regex]]
  namepass = ["OPTICAL_FREQUENCY", "OPTICAL_POWER"]

  [[processors.regex.tags]]
    key = "name"
    pattern = ".*PORT([0-9]+).*"
    replacement = "et-0/0/${1}"
    result_key = "interface"

[[processors.regex]]
  namepass = ["COMPONENT_STATE"]

  [[processors.regex.tags]]
    key         = "name"
    pattern     = "(?i)^Fan Tray \\d+ Fan (\\d+)$"
    replacement = "FAN_${1}"

