[[processors.rename]]
  namepass = ["QUEUE_STATE"]

  [[processors.rename.replace]]
    field = "queue/state/max_queue_len"
    dest  = "max_queue_len"

  [[processors.rename.replace]]
    field = "queue/state/avg_queue_len"
    dest  = "avg_queue_len"

  [[processors.rename.replace]]
    field = "queue/state/transmit_pkts"
    dest  = "transmit_pkts"

  [[processors.rename.replace]]
    field = "queue/state/transmit_octets"
    dest  = "transmit_octets"

  [[processors.rename.replace]]
    field = "queue/state/dropped_pkts"
    dest  = "dropped_pkts"

  [[processors.rename.replace]]
    field = "queue/state/dropped_octets"
    dest  = "dropped_octets"

[[processors.rename]]
  namepass = ["OPTICAL_FREQUENCY"]
  [[processors.rename.replace]]
    tag = "index"
    dest = "lane"

[[processors.rename]]
  namepass = ["QUEUE_STATE"]
  [[processors.rename.replace]]
    tag = "name"
    dest = "queue"

[[processors.rename]]
  namepass = ["BGP_SESSION_STATE", "BGP_STATE"]
  [[processors.rename.replace]]
    tag  = "/network-instances/network-instance/protocols/protocol/name"
    dest = "vrf"

[[processors.rename]]
  namepass = ["COMPONENT_STATE"]

  [[processors.rename.replace]]
    field = "temperature/instant"
    dest  = "instant"

  [[processors.rename.replace]]
    field = "temperature/avg"
    dest  = "avg"

  [[processors.rename.replace]]
    field = "temperature/min"
    dest  = "min"

  [[processors.rename.replace]]
    field = "temperature/max"
    dest  = "max"

  [[processors.rename.replace]]
    field = "temperature/interval"
    dest  = "interval_ns"   

  [[processors.rename.replace]]
    field = "temperature/min_time"
    dest  = "min_time"     

  [[processors.rename.replace]]
    field = "temperature/max_time"
    dest  = "max_time"     

  [[processors.rename.replace]]
    field = "temperature/alarm_status"
    dest  = "alarm_status"


[[processors.rename]]
  namepass = ["OSPF_GLOBAL"]
  [[processors.rename.replace]]
    field = "state/router_id"
    dest  = "router_id"
  [[processors.rename.replace]]
    field = "state/log_adjacency_changes"
    dest  = "log_adjacency_changes"