[[processors.starlark]]
  namepass = ["BGP_STATE"]
  source = '''
def apply(metric):
    v = metric.fields.get("last_established")
    if v != None:
        metric.fields["last_established"] = float(v) / 1e6  # ns -> s
    return metric
'''


[[processors.starlark]]
  namepass = ["OSPF_Neighbors"]
  source = '''
def apply(metric):
    promote = ["router_id", "designated_router", "backup_designated_router"]
    for field in promote:
        val = metric.fields.get("state/" + field) or metric.fields.get(field)
        if val:
            metric.tags[field] = str(val)
    return metric
'''


[[processors.starlark]]
  namepass = ["OSPF_Neighbors"]
  source = '''
def apply(metric):
    id = metric.tags.get("id")
    if id:
        metric.fields["interface_id"] = id
    return metric
'''

[[processors.starlark]]
  namepass = ["QUEUE_STATE"]
  order = 25
  source = '''
def apply(metric):
  for f in ["dropped_pkts","dropped_octets","max_queue_len","avg_queue_len"]:
    if f not in metric.fields:
      metric.fields[f] = 0
  return metric
'''
