{
 "title": "UbuntuVM",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU - addictional graphs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ubuntuVM_node_context_switches_total_counter)[1m]",
     "legendFormat": "switch context "
    },
    {
     "expr": "rate(ubuntuVM_node_intr_total_counter)",
     "legendFormat": "Interrupts counter"
    }
   ]
  },
  {
   "title": "I/O operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (device) (\r\n  rate(ubuntuVM_node_disk_io_time_seconds_total_counter{device != \"sr0\"}[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(ubuntuVM_node_cpu_seconds_total_counter{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Użycie CPU idle"
    },
    {
     "expr": "ubuntuVM_node_procs_running_gauge\r\n",
     "legendFormat": "Running process"
    },
    {
     "expr": "ubuntuVM_node_procs_blocked_gauge",
     "legendFormat": "Blocking process"
    },
    {
     "expr": "ubuntuVM_node_memory_SwapTotal_bytes_gauge",
     "legendFormat": "SWAP TOTAL"
    },
    {
     "expr": "ubuntuVM_node_memory_SwapFree_bytes_gauge\r\n",
     "legendFormat": "SWAP FREE"
    },
    {
     "expr": "(ubuntuVM_node_memory_SwapTotal_bytes_gauge - ubuntuVM_node_memory_SwapFree_bytes_gauge)\r\n  / ubuntuVM_node_memory_SwapTotal_bytes_gauge * 100\r\n",
     "legendFormat": "Użycie SWAP %"
    }
   ]
  },
  {
   "title": "Disc avg read bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(ubuntuVM_node_disk_read_bytes_total_counter[1m])",
     "legendFormat": "Device {{device}}"
    }
   ]
  },
  {
   "title": "ENS 18 INTERFACE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (device) (\r\n  rate(ubuntuVM_node_network_receive_bytes_total_counter{device!~\"lo|docker0\"}[1m])\r\n)\r\n",
     "legendFormat": "INCOMING {{device}}"
    },
    {
     "expr": "sum by (device) (\r\n  rate(ubuntuVM_node_network_transmit_bytes_total_counter{device!~\"lo|docker0\"}[1m])\r\n)\r\n",
     "legendFormat": "OUTCOMING {{device}}"
    },
    {
     "expr": "sum by (device) (\r\n  rate(ubuntuVM_node_network_receive_bytes_total_counter{device!~\"lo|docker0\"}[1m]) +\r\n  rate(ubuntuVM_node_network_transmit_bytes_total_counter{device!~\"lo|docker0\"}[1m])\r\n)\r\n",
     "legendFormat": "SUM {{device}}"
    }
   ]
  },
  {
   "title": "Disk storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(\r\n  (\r\n    ubuntuVM_node_filesystem_size_bytes_gauge{fstype!~\"tmpfs|overlay\"}\r\n    - ubuntuVM_node_filesystem_free_bytes_gauge{fstype!~\"tmpfs|overlay\"}\r\n  )\r\n  / ubuntuVM_node_filesystem_size_bytes_gauge{fstype!~\"tmpfs|overlay\"}\r\n) by (device) * 100\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}