[agent]
  interval = "30s"
  round_interval = true
  flush_interval = "15s"
  flush_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  logfile = ""
  hostname = "acx"
  omit_hostname = true

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.http]]
  url = "http://victoriametrics_gnmi:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"

# [[outputs.influxdb]]
#   urls = ["${DB_URL}"]
#   database = "${DB_NAME}"
#   skip_database_creation = true
#   content_encoding = "gzip"
#   precision = "ns"
