[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.http]]
  url = "http://victoriametrics_gnmi:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"

# [[outputs.influxdb]]
#   urls = ["${DB_URL}"]
#   database = "${DB_NAME}"
#   skip_database_creation = true
#   content_encoding = "gzip"
#   precision = "ns"
