[agent]
  interval = "30s"
  round_interval = true
  flush_interval = "15s"
  flush_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  logfile = ""
  hostname = "acx"
  omit_hostname = true

[[inputs.gnmi]]
  addresses = [ "${ACX_ADDRESSES}" ]
  username = "${GNMI_USERNAME}"
  password = "${GNMI_PASSWORD}" 
  tls_enable = true
  insecure_skip_verify = true
  encoding = "proto"
  redial = "60s"
  path_guessing_strategy = "subscription"
  depth = 1

  [[inputs.gnmi.subscription]]
    name = "INTERFACES"
    path = "/interfaces/interface/state/counters"
    sample_interval = "30s"
    subscription_mode = "sample"

  [[inputs.gnmi.subscription]]
    name = "TEMP"
    path = "/components/component/state/temperature"
    subscription_mode = "sample"
    sample_interval = "60s"

  [[inputs.gnmi.subscription]]
    name = "QUEUE"
    path = "/qos/interfaces/interface/output/queues"
    subscription_mode = "sample"
    sample_interval = "60s"
    suppress_redundant = true

  [[inputs.gnmi.subscription]]
    name = "SUBINTERFACES"
    path = "/interfaces/interface/subinterfaces/subinterface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "COMPONENT_STATE"
    path = "/components/component/state"
    subscription_mode = "sample"
    sample_interval = "60s"

  [[inputs.gnmi.subscription]]
    name = "OPTIC"
    path = "/components/component/transceiver"
    subscription_mode = "sample"
    sample_interval = "60s"

  [[inputs.gnmi.subscription]]
    name = "OCH"
    path = "/components/component/optical-channel"
    subscription_mode = "sample"
    sample_interval = "60s"

  [[inputs.gnmi.subscription]]
    name = "BGP_STATE"
    path = "/network-instances/network-instance[name=*]/protocols/protocol[identifier=BGP][name=*]/bgp/neighbors/neighbor[neighbor-address=*]/state"
    subscription_mode = "sample"
    sample_interval = "60s"

  [[inputs.gnmi.subscription]]
    name = "BGP_SESSION_STATE"
    path = "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state"
    subscription_mode = "sample"
    sample_interval = "10s"

[[processors.enum]]
  namepass = ["BGP_SESSION_STATE"]
  [[processors.enum.mapping]]
    field = "session_state"
    [processors.enum.mapping.value_mappings]
      "IDLE" = 1
      "ACTIVE" = 2
      "CONNECT" = 3
      "ESTABLISHED" = 4

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.http]]
  url = "http://victoriametrics_gnmi:8428/api/v1/import/prometheus"
  method = "POST"
  data_format = "prometheus"

# [[outputs.influxdb]]
#   urls = ["${DB_URL}"]
#   database = "${DB_NAME}"
#   skip_database_creation = true
#   content_encoding = "gzip"
#   precision = "ns"
